# Generated by Django 5.1.3 on 2024-12-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diretor',
            new_name='Director',
        ),
    ]
